name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          dart-version: '3.4.3'
          architecture: x64
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Update CocoaPods repos
        run: pod repo update
        working-directory: ios

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Create Payload directory
        run: mkdir Payload
        working-directory: build/ios/iphoneos

      - name: Move app to Payload
        run: mv Runner.app Payload
        working-directory: build/ios/iphoneos

      - name: Create IPA
        run: zip -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/iphoneos/FlutterIpaExport.ipa

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is the first release"
